# config.ini
# Configuration file for the script

# Define ubuntu type will be built: "CORE" is for Ubuntu Core
UBUNTU_TYPE="CORE"

# Clean all the previous build
CLEAN_ALL=0

# Define global variable (LXDE only):
WORK_DIR=$(pwd)
ROOTFS="./rootfs"
BIN_PATH="./rootfs/usr/bin"
SCRIPT_PATH="./script"

# Define the core-image-qt file name
core_image_qt_name="core-image-qt-rzpi.tar.bz2"

# Define bluetooth firmware link (LXDE only)
bluetooth_firmware_link="https://raw.githubusercontent.com/Realtek-OpenSource/android_hardware_realtek/rtk1395/bt/rtkbt/Firmware/BT/rtl8761b_fw"
bluetooth_firmware_target_folder="rootfs/lib/firmware/rtl_bt"
bluetooth_firmware_name="rtl8761bu_fw.bin"

# Define boot partition size in MB (should be larger than 100MB)
BOOT_SIZE_MB=200

# Define rootfs partition extra space in MB
ROOTFS_SPACE=5000

# Define ubuntu base file name and link that will be downloaded
# UBUNTU_BASE_FILE_NAME="ubuntu-base-18.04.5-base-arm64.tar.gz"
# UBUNTU_BASE_LINK="https://cdimage.ubuntu.com/ubuntu-base/releases/18.04/release/$UBUNTU_BASE_FILE_NAME"

# UBUNTU_BASE_FILE_NAME="ubuntu-base-20.04.1-base-arm64.tar.gz"
# UBUNTU_BASE_LINK="https://cdimage.ubuntu.com/ubuntu-base/releases/20.04/release/$UBUNTU_BASE_FILE_NAME"

#UBUNTU_BASE_FILE_NAME="ubuntu-base-22.04-base-arm64.tar.gz"
#UBUNTU_BASE_LINK="https://cdimage.ubuntu.com/ubuntu-base/releases/22.04/release/$UBUNTU_BASE_FILE_NAME"

UBUNTU_BASE_FILE_NAME="ubuntu-base-24.04.2-base-arm64.tar.gz"
UBUNTU_BASE_LINK="https://cdimage.ubuntu.com/ubuntu-base/releases/24.04/release/$UBUNTU_BASE_FILE_NAME"

# Define output rootfs file name
OUTPUT_ROOTFS="ubuntu-image-qt-rzpi"

# Define output wic file name
OUTPUT_WIC="ubuntu-image-qt-rzpi.wic"

# Time zone data (can be manually changed or dynamically retrieved from the host PC)
# TIME_ZONE_AREA="Etc"
# TIME_ZONE_CITY="UTC"
TIME_ZONE="$(cat /etc/timezone)"
TIME_ZONE_AREA="$(echo "$TIME_ZONE" | cut -d'/' -f1)"
TIME_ZONE_CITY="$(echo "$TIME_ZONE" | cut -d'/' -f2)"

# Setting this variable to 1 allows SSH login with empty passwords; setting it to 0 disallows such logins.
SSH_NO_PASS_LOGIN=1

#Weston launcher: 1 to enable, 0 to disable. Note: In this version, this feature is fixed as disabled; changing this setting will not affect the result.
IS_WESTON_ENABLE=0
