MACHINE ??= "rz-cmn"

# u-boot tagged: rz-cmn-srp-3.1-rc2
SRCREV_pn-u-boot = "rz-cmn-srp-3.1-rc2"

# trusted-firmware-a tagged: rz-cmn-srp-3.1-rc2
SRCREV_pn-trusted-firmware-a = "rz-cmn-srp-3.1-rc2"

# flash-writer tagged: rz-cmn-srp-3.1-rc2
SRCREV_pn-flash-writer = "rz-cmn-srp-3.1-rc2"

# rz-utils tagged: rz-cmn-srp-3.1-rc2
SRCREV_pn-universal-scripts = "rz-cmn-srp-3.1-rc2"
SRCREV_pn-binmake-native = "rz-cmn-srp-3.1-rc2"

# linux-yocto tagged: rz-cmn-srp-3.1-rc2
SRCREV_pn-linux-yocto = "rz-cmn-srp-3.1-rc2"
