MACHINE ??= "rzg2l-sbc"

# u-boot tagged: rz-cmn-srp-2.0-rc3
SRCREV_pn-u-boot = "rz-cmn-srp-2.0-rc3"

# trusted-firmware-a tagged: rz-cmn-srp-2.0-rc3
SRCREV_pn-trusted-firmware-a = "rz-cmn-srp-2.0-rc3"

# flash-writer tagged: rz-cmn-srp-2.0-rc3
SRCREV_pn-flash-writer = "rz-cmn-srp-2.0-rc3"
